function [ cnet ] = init( cnet )
%INIT Summary of this function goes here
%   Detailed explanation goes here
for it = 1:cnet.LayersNum
    cnet.Layer{it}.W = num2cell(zeros(1, cnet.Layer{it}.FMapNum));
    cnet.Layer{it}.B = num2cell(zeros(1, cnet.Layer{it}.FMapNum));
    for fm = 1:cnet.Layer{it}.FMapNum
        if cnet.Layer{it}.type == 's'
            cnet.Layer{it}.W{fm} = rand_std(1, ...
                1, ...
                cnet.Layer{it}.FMapNum);
            cnet.Layer{it}.B{fm} = rand_std(1, ...
                1, ...
                cnet.Layer{it}.FMapNum);
        elseif (cnet.Layer{it}.type == 'n' ||  cnet.Layer{it}.type == 'c')
            cnet.Layer{it}.W{fm} = ...
                zeros(cnet.Layer{it}.InputHeight, ...
                      cnet.Layer{it}.InputWidth, ...
                      size(cnet.Layer{it}.ConMap,2));
            
            for m= find(cnet.Layer{it}.ConMap(fm, :));
                cnet.Layer{it}.W{fm}(:,:,m) = ...
                    rand_std(cnet.Layer{it}.InputHeight, ...
                             cnet.Layer{it}.InputWidth, ...
                             cnet.Layer{it}.FMapNum);
            end
            cnet.Layer{it}.B{fm} = rand_std(1, ...
                                            1, ...
                                            cnet.Layer{it}.FMapNum);
        end
    end
    
    cnet.Layer{it}.Y = num2cell( zeros(1, cnet.Layer{it}.FMapNum) );
    cnet.Layer{it}.X = num2cell( zeros(1, cnet.Layer{it}.FMapNum) );
    
end

end

